# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
dependencies:
- base
- bytestring
- cassava
- aeson
- vector
- text
- pipes
- pipes-csv
- pipes-aeson
- pipes-safe
- pipes-text
- pipes-bytestring
- unordered-containers
- turtle
benchmarks:
  csv-to-json-benchmarks:
    dependencies:
    - csv-to-json
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: File
description: csv-to-json is a new Haskeleton package.
executables:
  csv-to-json:
    dependencies:
    - csv-to-json
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE
- package.yaml
- README.md
- stack.yaml
default-extensions:
- DataKinds
- DeriveDataTypeable
- DeriveGeneric
- DuplicateRecordFields
- FlexibleInstances
- GeneralizedNewtypeDeriving
- OverloadedStrings
- ScopedTypeVariables
- TemplateHaskell
- TypeOperators
ghc-options: -Wall
github: huseyinyilmaz/csv-to-json
library:
  source-dirs: library
license: MIT
maintainer: Huseyin Yilmaz
name: csv-to-json
synopsis: Command line format converter.
tests:
  csv-to-json-test-suite:
    dependencies:
    - base
    - csv-to-json
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0.1'
